### ISSUE TITLE
TN-RA: Additional fictitious attribute in RailwayLink

### ISSUE THREAD

**Issue by JohannaOtt** [INSPIRE-MIF/helpdesk#139]
According to the [network schema](https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/EARoot/EA3/EA1/EA5/EA9010.htm), the featureType Link contains an attribute ficticious.
According to the [Railway Transport Network schema](https://inspire.ec.europa.eu/data-model/approved/r4618-ir/html/EARoot/EA2/EA1/EA9/EA4/EA7508.htm), the featureType RailwayLink (which is inheriting from TransportLink which again is inheriting from Link) also has an attribut fictitious. Isn't that superfluous as the one from Link is already there?

**Comment by fabiovinci** [comment]
Dear @JohannaOtt,

you are right, it would be strange to have two identical attributes, moreover, with different requirements (one is mandatory and the other is voidable).

I think it is a typo in the UML and in the TG since the attribute `fictitious` is present in the old XSD ([RailwayTransportNetwork.xsd 3.1rc1](https://inspire.ec.europa.eu/draft-schemas/tn-ra/3.1rc1/RailwayTransportNetwork.xsd)) but is **not** present in the latest one ([RailwayTransportNetwork.xsd 4.0](https://inspire.ec.europa.eu/schemas/tn-ra/4.0/RailwayTransportNetwork.xsd)).

Version 4.0 of the XSD is correct since it contains only one attribute `fictitious` derived from the base Network application schema:

![image](https://user-images.githubusercontent.com/22212406/204281460-89fcfb36-34f8-4274-9857-8f05cad88968.png)

For this reason, I propose to close this issue and open a change proposal in the TG repository, what do you think?

If you agreed, could you please open a TG change proposal? Thanks

**Comment by heidivanparys** [comment]
Note that there is a [corrigendum](https://inspire.ec.europa.eu/file/1628/download?token=uAZgYLSk) to the [data specification for transport networks](https://inspire.ec.europa.eu/id/document/tg/tn). The third change described in there is regarding RailwayLink.fictitious:

![image](https://user-images.githubusercontent.com/11427611/204366935-223ff1a1-1f17-4899-9099-a55691e35042.png)

This change will be part of the upcoming amendment to the [implementing rules regarding interoperability](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02010R1089-20141231). I think the link to the latest public draft is this one: https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=PI_COM%3AAres%282021%295166256&qid=1669665607742, but please someone correct me if I'm wrong. See also [this presentation](https://wikis.ec.europa.eu/display/InspireMIG/16th+INSPIRE+back+to+back+MIG+and+MIG-T+meeting+on+2022-11-24+and+2022-11-25?preview=/68190468/68190734/PRES1_MIG16_COMInitiatives.pdf) from the last MIG meeting that includes an update in the amendment, but I can't find a direct link to the draft legislation in there.

In the current IR:

![image](https://user-images.githubusercontent.com/11427611/204370595-198e0030-477b-45fb-8a20-5480efc152ab.png)

In the proposed amendment:

![image](https://user-images.githubusercontent.com/11427611/204370657-012f10e4-a9b3-49c8-a670-bb3001de9daf.png)

I guess all three changes described in the corrigendum would have to be transformed into change proposals in the TG repository, perhaps influencing the [conversion plan](https://github.com/INSPIRE-MIF/technical-guidelines/blob/main/tg_conversion_plan.md)?

**Comment by JohannaOtt** [comment]
@heidivanparys Thanks for the hint, did not see that this has been addressed already.

@fabiovinci Do you know if the UML models in the UML repository as well as in the data specifications are aligned automatically if updates are made to the IR on data interoperability?

**Comment by fabiovinci** [comment]
Dear all,
for the changes present in the corrigenda a dedicated issue will be opened as soon as the related TG is available in GitHub.

The UML repository follows the same governance process as the schema repository, so it will be updated as soon as a change proposal related to schema and/or TG has an impact on UML.

**Comment by JohannaOtt** [comment]
@fabiovinci Thank you for clarification. IMO, this issue could be closed then.
