### ISSUE TITLE
Priority Datasets harmonisation - WFD, FD, END etc extended schemas

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk#3]
We are currently running an in-house project for the harmonization of the PDS.

We are aware of the ongoing work for the extension of the INSPIRE application schemas in order to cover the needs of specific reporting obligations, as regards the provision of spatial data. 

So the next reporting submissions for specific directives, like the WFD, the END, the FD, are going to include INSPIRE compliant datasets. 

The question is, what is the best way to address the compliance of the spatial datasets that were reported during previous reporting rounds? Should a MS use the relevant INSPIRE application schemas (eg. AM, EF etc) to harmonize already reported priority datasets or should we wait for the new extended application schemas?

What could be considered as a best practice?

**Comment by sMorrone** [comment]
Dear @grigoriouelena,
being datasets under the INSPIRE obligation, the PDS must meet the deadlines of the INSPIRE Roadmap. 

Therefore, since all relevant deadlines have already expired, PDS harmonisation shall not wait for the availability of INSPIRE-extended reporting schemas, and priority datasets must be provided in conformity with the pertinent INSPIRE application schemas.

Of course, having already performed an harmonisation process towards INSPIRE will represent an advantage when the corresponding reporting submissions are aligned to INSPIRE.

You might find it interesting having a look at the following posts regarding PDS harmonisation:
[Provision of noise exposure delineation Priority Datasets under the Human Health and Safety data theme](https://inspire.ec.europa.eu/forum/discussion/view/268807/provision-of-noise-exposure-delineation-priority-datasets-under-the-human-health-and-safety-data-theme-environmental-health-determinant-measure-spatial-objects)
[How to reuse existing data sets as INSPIRE Priority Datasets?](https://inspire.ec.europa.eu/forum/discussion/view/269779/how-to-reuse-existing-data-sets-as-inspire-priority-datasets)

**Comment by PfeifferM** [comment]
Dear all,
please note information in presentation from EEA:
https://circabc.europa.eu/sd/a/a8084b71-8d11-4393-bf87-8ae3b4cade45/WG%20DIS%20-%20EEA%20-%2020201020%20-%20INSPIRE%20Priority%20Data%20Sets.pdf
Best regards
Manuela
