### ISSUE TITLE
Use of UCUM to harmonize UnitOfMeasure in the Measure datatype.

### ISSUE THREAD

**Issue by wilkoquak** [INSPIRE-MIF/helpdesk#32]
Dear All,

In the INSPIRE data specifications Measure has been used to model Measurements. Part of a Measure element is a uom attribute that specifies the unit of meaure in which the value is stated, but no harmonized list of possible values is provided. A recent (well more recent than INSPIRE) initiative is the UCUM list ( https://ucum.org/trac ) which could act as a starting point for harmonization.

Now I have two questions:
- Is there any place in INSPIRE that discusses harmonizing values for Units of Meaure?
- If not, would UCUM be a good start?

Best wishes, Wilko Quak

**Comment by heidivanparys** [comment]
As for the first question: I am not aware of a such a place.

As for the second question: UCUM would be a good start indeed. According to [GML 3.2.2]:

> NOTE It is recommended that the symbol be an identifier for a unit of measure as specified in the “Unified Code of Units
> of Measure” (UCUM) (http://aurora.regenstrief.org/UCUM). This provides a set of symbols and a grammar for constructing
> identifiers for units of measure that are unique, and may be easily entered with a keyboard supporting the limited character set
> known as 7-bit ASCII. ISO 2955 formerly provided a specification with this scope, but was withdrawn in 2001. UCUM largely
> follows ISO 2955 with modifications to remove ambiguities and other problems.

Note, the URL to the spec has changed, it is now https://ucum.org/ucum.html instead of http://aurora.regenstrief.org/UCUM.

[GML 3.2.2] OGC. OGC 07-036r1, OpenGIS® Geography Markup Language (GML) Encoding Standard. Version 3.2.2. 5 December 2016. Available from: https://portal.opengeospatial.org/files/?artifact_id=74183&version=2

**Comment by heidivanparys** [comment]
See also the following statement from https://github.com/opengeospatial/geopackage/issues/386#issuecomment-325472698:

> In the OGC, most standards that have specific clauses related to UoM typically reference UCUM as the normative vocabulary.

**Comment by heidivanparys** [comment]
This issue is also related to this discussion.

From the [public slides of the last OGC member meeting](https://portal.ogc.org/files/97133):

![billede](https://user-images.githubusercontent.com/11427611/120709044-a9681b00-c4bc-11eb-9dc8-2063a781e007.png)

I am not sure whether that means that UCUM will be deprecated. It may depend on the encoding: for use in LinkedIn URIs are needed, for other encodings UCUM may be more suitable.

**Comment by wilkoquak** [comment]
Dear Heidi, thank for all you responses. Somehow I missed the UCUM recommendation in the GML standard. A thing that COULD be done to enhance interoperability in INSPIRE is make it obligatory to use UCUM whenever possible and provide URI's for missing units of measure in the INSPIRE code list register.
