### ISSUE TITLE
Application schema to use for the harmonization of the FD reporting data

### ISSUE THREAD

**Issue by grigoriouelena** [INSPIRE-MIF/helpdesk#4]
During the process of the harmonization of the FD reporting data, we found that the reporting schema published by the EEA (http://dd.eionet.europa.eu/schemaset/Floods/view) does not seem to be Inspire compliant as it is not a formal specialization of the NaturalRiskZones application schema, e.g. the 'Identifier' data type in the reporting schema is not imported from the Inspire Base Types application schema.

Are there any suggestions about which application schema should be used to harmonize the FD reporting data?

**Comment by sMorrone** [comment]
Dear @grigoriouelena,
to date, the alignment to INSPIRE of the Floods Directive (FD) reporting occurs only at a ‘conceptual’ level - i.e. the data model development phase considered the relevant elements from INSPIRE but then the creation of reporting schemas did not follow [ INSPIRE extension patterns](http://inspire-extensions.wetransform.to/patterns/index.html). 
For this reason, as you correctly pointed out, data provided according to FD schemas does not conform to INSPIRE requirements.
If, on the one hand, the major goal of INSPIRE PDS is to first and foremost encourage the availability of thematic data through INSPIRE infrastructure (so firstly data made available ‘as-is’, then full harmonisation to INSPIRE requirements in a stepwise manner), on the other the deadlines of the INSPIRE implementation roadmap apply also to harmonisation of Priority Datasets.
Therefore, since all relevant deadlines have already expired, Priority Datasets must be provided in conformity with the pertinent INSPIRE application schemas.
A consistent mapping of priority datasets to INSPIRE themes /application schemas /spatial objects by the Member States is crucial for the creation of pan-European data sets and relevant guidance can be found in the  “**Mapping to INSPIRE themes**” section of the PDS excel table, whose last revised version 2.1 can be downloaded  [here](https://webgate.ec.europa.eu/fpfis/wikis/download/attachments/299729499/eReporting_PriorityDataList_V2.1_final_withcomments_20201008.xlsx?version=1&modificationDate=1602228162165&api=v2)

**Comment by sMorrone** [comment]
Dear @grigoriouelena,
has your question been fully answered? ? do you still have doubts or can we consider this issue closed?

**Comment by grigoriouelena** [comment]
Dear @sMorrone,

Yes, the question is answered. I am closing this issue with this comment.
