### ISSUE TITLE
How to check codelists's relations in the UML Consolidated Model?

### ISSUE THREAD

**Issue by Ceprey2** [INSPIRE-MIF/helpdesk#46]
![codelistRelation](https://user-images.githubusercontent.com/25895406/126940161-7bb56309-a26b-41c9-a125-3216e8bea8a3.JPG)
Hi,
I'm just trying to find out to which type/attributes is each codelist related? How to find the stereotype in the UML Consolidated Model they hold the values for? For example, "ClassificationAndQuantificationFrameworkValue", "Renewable and Waste Value", "FossilFuelValue"?

**Comment by KathiSchleidt** [comment]
Trying to see what you're looking for, the codelists? See:
https://inspire.ec.europa.eu/registry

e.g. https://inspire.ec.europa.eu/codelist/ClassificationAndQuantificationFrameworkValue

**Comment by Ceprey2** [comment]
Thank you for your reply, I've checked the indicated sources. Unfortunately, I could not see the clear indication of the stereotypes to which this codelist provides values. In some schemas this linkage between an attribute and a codelist are intuitively visible, like in the image ("SpecialisedEMFTypeValue"), but in the case I do not see that similar naming, I cannot understand to which stereotype/attribute it provides values, like in my previous example with the Fossils. Any idea of how to see, to which stereotype they provide values?
![codelistSpecialisedMonitoringExample](https://user-images.githubusercontent.com/25895406/127115710-a20962ee-ae1a-48a6-9237-5f05e9b228f8.JPG)

Thanks in advance,
Serhii

**Comment by sMorrone** [comment]
Dear @Ceprey2 ,
are you asking for the matching between the code list and the relevant attribute(s)? In screenshot below the example for the ClassificationAndQuantificationFrameworkValue, 
![image](https://user-images.githubusercontent.com/13329248/127119486-92ed163e-d069-461c-b728-d13555d90edc.png)
In that case, you will find all that is needed in the Data Specification documents and therein contained Feature catalogues.
Since version 4.0 of the schemas, the code list attributes are encoded as gml:ReferenceType. For example:
![image](https://user-images.githubusercontent.com/13329248/127121111-de5c6c9a-6cad-4db1-977d-833407e7f93b.png).

You might find as well very useful the Catalogue of INSPIRE Objects from the Find your scope application (see quick links section of the website)
![image](https://user-images.githubusercontent.com/13329248/127121644-fbf059e8-ba29-4a5a-8ad0-e78f9d80b6f3.png)

Does this help?

**Comment by Ceprey2** [comment]
Dear sMorrone, 
Thank you so much for your explanations and provided resources.
I could find "FossilFuelClassValue" as a codelist of the claasse"AggregatedResource", attribute "resourceClass". But, unfortunately, I cannot find the "AggregatedResource". But, unfortunately, it cannot be located in the approved UML model https://inspire.ec.europa.eu/portfolio/data-models   Does it mean that the UML model does not represent all the classes and attributes, and for the whole pictuer and  details it is recommended to look into specifications? 
![FossilClassValueCodelist](https://user-images.githubusercontent.com/25895406/127152877-ad35c684-de71-480c-8a86-85d78cc7b8c3.JPG)

**Comment by Ceprey2** [comment]
Ok, got it, I see these codelists are just declared in a schema of origin and are  to be found in other application schemas. It is clear now, thank you.
