### ISSUE TITLE
Not all the documentation on https://inspire-geoportal.ec.europa.eu/mr2020.htm is direct available

### ISSUE THREAD

**Issue by wboersma** [INSPIRE-MIF/helpdesk#74]
Hello helpdesk,

Not all the documents (under Documentation)  on https://inspire-geoportal.ec.europa.eu/mr2020.htm are direct available. 
For these 2 documents you have to login:
- Guidance document for the calculation of indicators 
- Indicators calculation 
 
Is it possible to have direct access to these documents.

Best regards, Wideke

**Comment by heidivanparys** [comment]
Hi Wideke, I am not sure what links you refer to, the link above gives me “The page you were looking for appears to have been moved, deleted or does not exist in the INSPIRE Geoportal.”. I can't find anything called “Documentation” either.

However, it is possible to find all resources regarding monitoring and reporting on https://inspire.ec.europa.eu/document-tags/monitoring-and-reporting. In particular, there is [INSPIRE Monitoring Indicators – Guidelines Document](https://inspire.ec.europa.eu/documents/inspire-monitoring-indicators-%E2%80%93-guidelines-document-0).

Does this help?

**Comment by reinij** [comment]
Hi Wideke, Heidi,

In original URL there was a typo, the correct link is https://inspire-geoportal.ec.europa.eu/mr2020.html.
At the bottom you have links to these two docs mentioned, and indeed, both of them require EU Login. I'm not sure if documents linked by @heidivanparys are identical.

**Comment by wboersma** [comment]
Hi Heidi,

I see the url is not complete (sorry): https://inspire-geoportal.ec.europa.eu/mr2020.html. At the bottom of this page you find the documentation.
The document INSPIRE Monitoring Indicators – Guidelines Document you refer to, is an old one (2013). And also under https://inspire.ec.europa.eu/document-tags/monitoring-and-reporting I couldn't find the new one guidance document .

Best regards, Wideke

**Comment by heidivanparys** [comment]
[10th MIG meeting](https://wikis.ec.europa.eu/display/InspireMIG/10th+MIG+meeting+2019-06-20):

- [Guidance document for the calculation of indicators (PDF)](https://wikis.ec.europa.eu/download/attachments/33527444/%5BDOC6%5D_MIG10_IndicatorsGuide.pdf?version=1&modificationDate=1560513159335&api=v2)
- [Guidance document for the calculation of indicators (DOCX)](https://wikis.ec.europa.eu/download/attachments/33527444/%5BDOC6%5D_MIG10_IndicatorsGuide.docx?version=1&modificationDate=1560513150567&api=v2)

[66th MIG-T meeting](https://wikis.ec.europa.eu/pages/viewpage.action?pageId=33528098):

- [Indicators calculation (PPTX)](https://wikis.ec.europa.eu/download/attachments/33528098/PRES-1.1%20Indicators%20%28JRC%29.pptx?version=1&modificationDate=1629367587468&api=v2)

I assume the JRC/EU has been doing changes to the wiki a while ago, I noticed the same issue with login required earlier, for other things. You can navigate using the menu on the left on https://wikis.ec.europa.eu/pages/viewpage.action?pageId=33527401, links starting with `https://wikis.ec.europa.eu` seem to be accessible without login.

Someone (@jescriu, @alexanderkotsev, @MarcoMinghini?) should update the links on https://inspire-geoportal.ec.europa.eu/mr2020.html

**Comment by wboersma** [comment]
Heidi, thank you. In the pdf/doc are still red XXX. Is there also a version where the xxx is a real number?

**Comment by heidivanparys** [comment]
I double-checked the minutes of the MIG meetings, and [searched the whole wiki](https://wikis.ec.europa.eu/dosearchsite.action?cql=siteSearch+~+%22guidance+calculation+indicators%22&queryString=guidance+calculation+indicators), but I haven't found a document that is more recent than the one referred to above.

**Comment by wboersma** [comment]
Thanks Heidi! I use the documents, you mentioned earlier

**Comment by sMorrone** [comment]
Dear @wboersma
was your question fully answered? can we proceed to close this issue?

**Comment by wboersma** [comment]
Dear @sMorrone ,

My question is answered, but the links should be updated. See above.

**Comment by MarcoMinghini** [comment]
Dear @wboersma and @heidivanparys,
thanks for initiating this discussion. Our views are the following:

- the documents linked from the [2020 M&R page](https://inspire-geoportal.ec.europa.eu/mr2020.html) are accessible after logging in through EU Login. Everyone can create an EU Login account, so we do not see this as a barrier to access the documents.

- regarding the [Guidance document for the calculation of indicators](https://wikis.ec.europa.eu/download/attachments/33527444/%5BDOC6%5D_MIG10_IndicatorsGuide.pdf?version=1&modificationDate=1560513159335&api=v2), this is still including the "XXX" because it was produced for the purpose of [MIG meeting 10](https://wikis.ec.europa.eu/display/InspireMIG/10th+MIG+meeting+2019-06-20) in June 2019, i.e. before the Commission Decision was published. There is no other version in addition to this one.

- Good idea to update the [Monitoring and Reporting page on the IKB](https://inspire.ec.europa.eu/document-tags/monitoring-and-reporting). Instead of adding the same documents you mentioned (one of which has the issue above - it is a MIG document and includes "XXX" - while the other is only a presentation that does not include the full details on the indicators), we decided to include the link to the [JRC Technical Report](https://publications.jrc.ec.europa.eu/repository/handle/JRC122351) that we published to explain the process/share the results of M&R 2019 (the first M&R based on the new set of indicators). In Section 2 of this report, you can find exactly the same explanation of all the indicators included in the guidance document mentioned above.

I hope this solves all doubts. I leave the issue closed, but feel free to re-open it in case there are additional questions or points to discuss.
